name: Spell checking
on:
  pull_request_target:
  push:

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 5
    - uses: check-spelling/check-spelling@main
      with:
        config: .github/actions/spell-check
        extra_dictionaries:
          cspell:cpp/cpp.txt
          cspell:html/html.txt
          cspell:css/css.txt
          cspell:filetypes/filetypes.txt
